GET http://localhost:7000/user/getusers

###
POST http://localhost:7000/user/createuser
Content-Type:application/json

{
    "firstName":"Tejaswini",
    "lastName":"Kothuru",
    "gender":"female",
    "dateOfBirth":"01/04/1999",
    "email":"tejaswinikothuru@gmail.com",
    "password":"Tejaswini@1"
}

###
PUT http://localhost:4000/notes/updatednote
Content-Type: application/json

{
    "title":"KeepNotes",
    "description":"welcome to keep notes. Team-6 Teju swathi khairun nischala"
}

###
POST  http://localhost:7000/user/login
Content-Type: application/json

{
    "email":"tejaswinikothuru@gmail.com",
    "password":"Tejaswini@1"
}

###
GET http://localhost:4000/notes/getnotes

###
POST http://localhost:4000/notes/createnotes
Content-Type: application/json

{
    "title":"KeepNotes",
    "description":" Welcome To KeepNotes",
    "status":"true",
    "archive":"true"
}

###
POST http://localhost:5000/notes/deletenote
Content-Type: application/json

{
    "title":"KeepNotes",
    "description":" Welcome To KeepNotes"
}

###
GET http://localhost:5000/notes/getdeletednotes

###
POST http://localhost:5000/notes/restorenote
Content-Type: application/json

{
    "title":"KeepNotes"
}

###
POST http://localhost:5000/notes/archivenote
Content-Type: application/json

{
    "title":"KeepNotes"
}

###
POST http://localhost:5000/notes/undo

{
    "title":"KeepNotes"
}

###
GET http://localhost:5000/notes/getarchivednotes

###
GET http://localhost:7000/reminder/getreminder

###
POST http://localhost:7000/reminder/createreminder
Content-Type: application/json

{
    "title":"KeepNotes",
    "description":" Welcome To KeepNotes"
}

###
DELETE http://localhost:5000/reminder/removereminder/KeepNotes

###
GET http://localhost:5000/favourite/getfavourite

###
POST http://localhost:5000/favourite/createfavourite
Content-Type: application/json

{
    "title":"KeepNotes",
    "description":" Welcome To KeepNotes"
}

###
DELETE http://localhost:5000/favourite/removefavourite/KeepNotes

###
GET http://localhost:4000/user/getusers
 
###
POST http://localhost:4000/user/createuser
Content-Type: application/json

{
    "firstName":"Tejaswini",
    "lastName":"Kothuru",
    "gender":"female",
    "dateOfBirth":"01/04/1999",
    "email":"tejaswinikothuru@gmail.com",
    "password":"Tejaswini@1"
}


###
POST http://localhost:4000/user/login
Content-Type: application/json

{
    "email":"tejaswinikothuru@gmail.com",
    "password":"Tejaswini@1"
}

###
POST http://localhost:4000/notes/createnotes
Content-Type: application/json

{
    "title":"title",
    "description":"abc",  
    "status":"true",
    "archive":"true"
}

###
DELETE http://localhost:4000/notes/permanentdelete/title
###
GET http://localhost:4000/notes/getnotes
 
###
POST http://localhost:6000/notes/deletenote
Content-Type:application/json

{
    "title":"title",
    "description":"abc"
}
 
###
GET http://localhost:6000/notes/getarchivednotes
 
###
POST http://localhost:6000/notes/undo
Content-Type:application/json

{
    "title":"title",
    "description":"abc"
}


###
POST http://localhost:5000/favourite/createfavourite
Content-Type:application/json
 
{​​​​​​​​
"title":"a",
"description":"aaa"
}​​​​​​​​
 
###
GET http://localhost:5000/favourite/getfavourites
 
###
DELETE http://localhost:5000/favourite/removefavourite/a
Content-Type:application/json
 
{​​​​​​​​
"title":"a",
"description":"aaa"
}​​​​​​​​
 

###
GET http://localhost:4000/reminder/getreminder

###
POST http://localhost:4000/reminder/createreminder
Content-Type: application/json

{
    "title":"KeepNotes",
    "description":" Welcome To KeepNotes"
}

###
DELETE http://localhost:4000/reminder/removereminder/KeepNotes


###
GET http://localhost:4000/favourite/getfavourite

###
POST http://localhost:4000/favourite/createfavourite
Content-Type: application/json

{
    "title":"KeepNotes",
    "description":" Welcome To KeepNotes"
}

###
DELETE http://localhost:4000/favourite/removefavourite/KeepNotes
